language: node_js
branches:
  only:
    - master
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: SteveGoodRocks
  space: production
node_js:
  - "0.10.40"
notifications:
  email:
    recipients:
      - sgood@lanctr.com
